### ISSUE TITLE
tag缺失问题

### ISSUE THREAD

**Issue by CChengjie** [houbb/heaven#4]
我正在做一个关于tag的研究，在这个项目中所有发布都没有打tag，而是直接建立的分支，那么就假设branch就是release tag啦。
我们发现了0.1.133版本在maven中发布了，但是github中并没有相应的tag（branch）

1）请问tag缺失的原因是什么？（发现有相关commit message）

- a、该版本存在代码问题，如存在漏洞、兼容性问题、界面方面问题等。
- b、该版本出现功能性问题，如功能规划不合理、基础功能不能使用等。
- c、忘记打tag
- d、不在意或者嫌操作麻烦
- e、该版本没有必要打tag
- f、其他原因，_

2） 针对该问题，我们提出了一个方法，能够找到version 可能对应的真实commit， 以帮助开发者快速定位问题代码，完成漏洞修复。 以下是我们方法给出的可能的真实commits，请您帮忙确认下是否包含了真实的commit，如果不是，应该是哪一个？
发布**0.1.33**的是否为该commit：
**[‘3e48033cf211ac37a05f45c7210547c0df315b08’]**
这个问题对我们的调研非常重要，感谢能抽空解答QAQ

**Comment by houbb** [comment]
个人习惯，不喜欢使用 TAG。
